# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ridesharing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ridesharing.proto\x12\x0bridesharing\"M\n\x0bRideRequest\x12\x10\n\x08rider_id\x18\x01 \x01(\t\x12\x17\n\x0fpickup_location\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\"Z\n\x0cRideResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\tdriver_id\x18\x03 \x01(\t\x12\x16\n\x0e\x65stimated_time\x18\x04 \x01(\t\"$\n\x11RideStatusRequest\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\"$\n\x12RideStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"7\n\x11\x41\x63\x63\x65ptRideRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0f\n\x07ride_id\x18\x02 \x01(\t\"$\n\x12\x41\x63\x63\x65ptRideResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"7\n\x11RejectRideRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0f\n\x07ride_id\x18\x02 \x01(\t\"$\n\x12RejectRideResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\";\n\x15RideCompletionRequest\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\"(\n\x16RideCompletionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9a\x03\n\x0bRideSharing\x12\x42\n\x0bRequestRide\x12\x18.ridesharing.RideRequest\x1a\x19.ridesharing.RideResponse\x12P\n\rGetRideStatus\x12\x1e.ridesharing.RideStatusRequest\x1a\x1f.ridesharing.RideStatusResponse\x12M\n\nAcceptRide\x12\x1e.ridesharing.AcceptRideRequest\x1a\x1f.ridesharing.AcceptRideResponse\x12M\n\nRejectRide\x12\x1e.ridesharing.RejectRideRequest\x1a\x1f.ridesharing.RejectRideResponse\x12W\n\x0c\x43ompleteRide\x12\".ridesharing.RideCompletionRequest\x1a#.ridesharing.RideCompletionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ridesharing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RIDEREQUEST']._serialized_start=34
  _globals['_RIDEREQUEST']._serialized_end=111
  _globals['_RIDERESPONSE']._serialized_start=113
  _globals['_RIDERESPONSE']._serialized_end=203
  _globals['_RIDESTATUSREQUEST']._serialized_start=205
  _globals['_RIDESTATUSREQUEST']._serialized_end=241
  _globals['_RIDESTATUSRESPONSE']._serialized_start=243
  _globals['_RIDESTATUSRESPONSE']._serialized_end=279
  _globals['_ACCEPTRIDEREQUEST']._serialized_start=281
  _globals['_ACCEPTRIDEREQUEST']._serialized_end=336
  _globals['_ACCEPTRIDERESPONSE']._serialized_start=338
  _globals['_ACCEPTRIDERESPONSE']._serialized_end=374
  _globals['_REJECTRIDEREQUEST']._serialized_start=376
  _globals['_REJECTRIDEREQUEST']._serialized_end=431
  _globals['_REJECTRIDERESPONSE']._serialized_start=433
  _globals['_REJECTRIDERESPONSE']._serialized_end=469
  _globals['_RIDECOMPLETIONREQUEST']._serialized_start=471
  _globals['_RIDECOMPLETIONREQUEST']._serialized_end=530
  _globals['_RIDECOMPLETIONRESPONSE']._serialized_start=532
  _globals['_RIDECOMPLETIONRESPONSE']._serialized_end=572
  _globals['_RIDESHARING']._serialized_start=575
  _globals['_RIDESHARING']._serialized_end=985
# @@protoc_insertion_point(module_scope)
